import ol_style_FontSymbol from 'ol-ext/style/FontSymbol'

/* Copyright (c) 2014 by Jean-Marc.Viglino [at]ign.fr
* Dual-licensed under the CeCILL-B Licence (http://www.cecill.info/)
* and the Beerware license (http://en.wikipedia.org/wiki/Beerware),
* feel free to use and abuse it in your projects (the code, not the beer ;-).
*
* Font definiton to use with fontsymbols
*/
ol_style_FontSymbol.addDefs ({
  'font': 'evilz',
  'name': 'Evilz',
  'copyright': '(C) N+ Sakurai Nan aka "Bosskete"',
  'prefix': 'evilz',
}, {
  'evilz-potion-croix': {'font': 'evilz', 'code': 59392, 'theme': 'evilz', 'name': 'croix', 'search': 'potion,croix'},
  'evilz-potion-coeur': {'font': 'evilz', 'code': 59393, 'theme': 'evilz', 'name': 'coeur', 'search': 'potion,coeur'},
  'evilz-plume': {'font': 'evilz', 'code': 59394, 'name': 'plume', 'search': 'plume', 'theme': 'evilz'},
  'evilz-maison': {'font': 'evilz', 'code': 59395, 'name': 'maison', 'search': 'maison', 'theme': 'evilz'},
  'evilz-lutin-prisonnier': {'font': 'evilz', 'code': 59396, 'theme': 'evilz', 'name': 'prisonnier', 'search': 'lutin,prisonnier'},
  'evilz-lutin-mort': {'font': 'evilz', 'code': 59397, 'theme': 'evilz', 'name': 'mort', 'search': 'lutin,mort'},
  'evilz-lutin-marchant': {'font': 'evilz', 'code': 59398, 'theme': 'evilz', 'name': 'marchant', 'search': 'lutin,marchant'},
  'evilz-lutin-lutin': {'font': 'evilz', 'code': 59399, 'theme': 'evilz', 'name': 'lutin', 'search': 'lutin,lutin'},
  'evilz-lutin-fourche': {'font': 'evilz', 'code': 59400, 'theme': 'evilz', 'name': 'fourche', 'search': 'lutin,fourche'},
  'evilz-lutin-diable': {'font': 'evilz', 'code': 59401, 'theme': 'evilz', 'name': 'diable', 'search': 'lutin,diable'},
  'evilz-lutin-bouffon': {'font': 'evilz', 'code': 59402, 'theme': 'evilz', 'name': 'bouffon', 'search': 'lutin,bouffon'},
  'evilz-lune': {'font': 'evilz', 'code': 59403, 'name': 'lune', 'search': 'lune', 'theme': 'evilz'},
  'evilz-loup': {'font': 'evilz', 'code': 59404, 'name': 'loup', 'search': 'loup', 'theme': 'evilz'},
  'evilz-lezard': {'font': 'evilz', 'code': 59405, 'name': 'lezard', 'search': 'lezard', 'theme': 'evilz'},
  'evilz-fantome-tendre': {'font': 'evilz', 'code': 59406, 'theme': 'evilz', 'name': 'tendre', 'search': 'fantome,tendre'},
  'evilz-griffes': {'font': 'evilz', 'code': 59407, 'name': 'griffes', 'search': 'griffes', 'theme': 'evilz'},
  'evilz-fantome-petit': {'font': 'evilz', 'code': 59408, 'theme': 'evilz', 'name': 'petit', 'search': 'fantome,petit'},
  'evilz-fantome-faceur': {'font': 'evilz', 'code': 59409, 'theme': 'evilz', 'name': 'faceur', 'search': 'fantome,faceur'},
  'evilz-fantome-lapin': {'font': 'evilz', 'code': 59410, 'theme': 'evilz', 'name': 'lapin', 'search': 'fantome,lapin'},
  'evilz-face-vampire': {'font': 'evilz', 'code': 59411, 'theme': 'evilz', 'name': 'vampire', 'search': 'face,vampire'},
  'evilz-fantome-citrouille': {'font': 'evilz', 'code': 59412, 'theme': 'evilz', 'name': 'citrouille', 'search': 'fantome,citrouille'},
  'evilz-face-rieur': {'font': 'evilz', 'code': 59413, 'theme': 'evilz', 'name': 'rieur', 'search': 'face,rieur'},
  'evilz-face-mickey': {'font': 'evilz', 'code': 59414, 'theme': 'evilz', 'name': 'mickey', 'search': 'face,mickey'},
  'evilz-face-lapin': {'font': 'evilz', 'code': 59415, 'theme': 'evilz', 'name': 'lapin', 'search': 'face,lapin'},
  'evilz-face-fumeur': {'font': 'evilz', 'code': 59416, 'theme': 'evilz', 'name': 'fumeur', 'search': 'face,fumeur'},
  'evilz-face-coupee': {'font': 'evilz', 'code': 59417, 'theme': 'evilz', 'name': 'coupee', 'search': 'face,coupee'},
  'evilz-face-cuir': {'font': 'evilz', 'code': 59418, 'theme': 'evilz', 'name': 'cuir', 'search': 'face,cuir'},
  'evilz-face-chat': {'font': 'evilz', 'code': 59419, 'theme': 'evilz', 'name': 'chat', 'search': 'face,chat'},
  'evilz-face-bouffon': {'font': 'evilz', 'code': 59420, 'theme': 'evilz', 'name': 'bouffon', 'search': 'face,bouffon'},
  'evilz-etoile-os': {'font': 'evilz', 'code': 59421, 'theme': 'evilz', 'name': 'os', 'search': 'etoile,os'},
  'evilz-etoile-pentacle': {'font': 'evilz', 'code': 59422, 'theme': 'evilz', 'name': 'pentacle', 'search': 'etoile,pentacle'},
  'evilz-etoile-mort': {'font': 'evilz', 'code': 59423, 'theme': 'evilz', 'name': 'mort', 'search': 'etoile,mort'},
  'evilz-epines': {'font': 'evilz', 'code': 59424, 'name': 'epines', 'search': 'epines', 'theme': 'evilz'},
  'evilz-des': {'font': 'evilz', 'code': 59425, 'name': 'des', 'search': 'des', 'theme': 'evilz'},
  'evilz-croix-os': {'font': 'evilz', 'code': 59426, 'theme': 'evilz', 'name': 'os', 'search': 'croix,os'},
  'evilz-croix-croix': {'font': 'evilz', 'code': 59427, 'theme': 'evilz', 'name': 'croix', 'search': 'croix,croix'},
  'evilz-corbeau': {'font': 'evilz', 'code': 59428, 'name': 'corbeau', 'search': 'corbeau', 'theme': 'evilz'},
  'evilz-coeur-mort': {'font': 'evilz', 'code': 59429, 'theme': 'evilz', 'name': 'mort', 'search': 'coeur,mort'},
  'evilz-coeur-eclair': {'font': 'evilz', 'code': 59430, 'theme': 'evilz', 'name': 'eclair', 'search': 'coeur,eclair'},
  'evilz-coeur-croix': {'font': 'evilz', 'code': 59431, 'theme': 'evilz', 'name': 'croix', 'search': 'coeur,croix'},
  'evilz-coeur-aile': {'font': 'evilz', 'code': 59432, 'theme': 'evilz', 'name': 'aile', 'search': 'coeur,aile'},
  'evilz-cle-mort': {'font': 'evilz', 'code': 59433, 'theme': 'evilz', 'name': 'mort', 'search': 'cle,mort'},
  'evilz-cle-chat': {'font': 'evilz', 'code': 59434, 'theme': 'evilz', 'name': 'chat', 'search': 'cle,chat'},
  'evilz-citrouille': {'font': 'evilz', 'code': 59435, 'name': 'citrouille', 'search': 'citrouille', 'theme': 'evilz'},
  'evilz-cimetiere': {'font': 'evilz', 'code': 59436, 'name': 'cimetiere', 'search': 'cimetiere', 'theme': 'evilz'},
  'evilz-chouette': {'font': 'evilz', 'code': 59437, 'name': 'chouette', 'search': 'chouette', 'theme': 'evilz'},
  'evilz-chauve_souris': {'font': 'evilz', 'code': 59438, 'name': 'chauve_souris', 'search': 'chauve_souris', 'theme': 'evilz'},
  'evilz-chat': {'font': 'evilz', 'code': 59439, 'name': 'chat', 'search': 'chat', 'theme': 'evilz'},
  'evilz-cerceuil': {'font': 'evilz', 'code': 59440, 'name': 'cerceuil', 'search': 'cerceuil', 'theme': 'evilz'},
  'evilz-bougie': {'font': 'evilz', 'code': 59441, 'name': 'bougie', 'search': 'bougie', 'theme': 'evilz'},
  'evilz-bougeoire': {'font': 'evilz', 'code': 59442, 'name': 'bougeoire', 'search': 'bougeoire', 'theme': 'evilz'},
  'evilz-arme-hache': {'font': 'evilz', 'code': 59443, 'theme': 'evilz', 'name': 'hache', 'search': 'arme,hache'},
  'evilz-arme-fleau': {'font': 'evilz', 'code': 59444, 'theme': 'evilz', 'name': 'fleau', 'search': 'arme,fleau'},
  'evilz-arme-epees': {'font': 'evilz', 'code': 59445, 'theme': 'evilz', 'name': 'epees', 'search': 'arme,epees'},
  'evilz-arme-epee': {'font': 'evilz', 'code': 59446, 'theme': 'evilz', 'name': 'epee', 'search': 'arme,epee'},
  'evilz-arme-bombe': {'font': 'evilz', 'code': 59447, 'theme': 'evilz', 'name': 'bombe', 'search': 'arme,bombe'},
  'evilz-araignee': {'font': 'evilz', 'code': 59448, 'name': 'araignee', 'search': 'araignee', 'theme': 'evilz'},
  'evilz-warning': {'font': 'evilz', 'code': 59449, 'name': 'warning', 'search': 'warning', 'theme': 'evilz'},
  'evilz-toile': {'font': 'evilz', 'code': 59450, 'name': 'toile', 'search': 'toile', 'theme': 'evilz'},
  'evilz-tete-roi': {'font': 'evilz', 'code': 59451, 'theme': 'evilz', 'name': 'roi', 'search': 'tete,roi'},
  'evilz-tete-pirate': {'font': 'evilz', 'code': 59452, 'theme': 'evilz', 'name': 'pirate', 'search': 'tete,pirate'},
  'evilz-tete-os': {'font': 'evilz', 'code': 59453, 'theme': 'evilz', 'name': 'os', 'search': 'tete,os'},
  'evilz-tete-mort': {'font': 'evilz', 'code': 59454, 'theme': 'evilz', 'name': 'mort', 'search': 'tete,mort'},
  'evilz-tete-croix': {'font': 'evilz', 'code': 59455, 'theme': 'evilz', 'name': 'croix', 'search': 'tete,croix'},
  'evilz-tete-corne': {'font': 'evilz', 'code': 59456, 'theme': 'evilz', 'name': 'corne', 'search': 'tete,corne'},
  'evilz-tache': {'font': 'evilz', 'code': 59457, 'name': 'tache', 'search': 'tache', 'theme': 'evilz'},
  'evilz-sorciere-chapeau': {'font': 'evilz', 'code': 59458, 'theme': 'evilz', 'name': 'chapeau', 'search': 'sorciere,chapeau'},
  'evilz-sorciere-baton': {'font': 'evilz', 'code': 59459, 'theme': 'evilz', 'name': 'baton', 'search': 'sorciere,baton'},
  'evilz-serpents': {'font': 'evilz', 'code': 59460, 'name': 'serpents', 'search': 'serpents', 'theme': 'evilz'},
  'evilz-serpentin': {'font': 'evilz', 'code': 59461, 'name': 'serpentin', 'search': 'serpentin', 'theme': 'evilz'},
  'evilz-serpent': {'font': 'evilz', 'code': 59462, 'name': 'serpent', 'search': 'serpent', 'theme': 'evilz'},
  'evilz-sac-dollar': {'font': 'evilz', 'code': 59463, 'theme': 'evilz', 'name': 'dollar', 'search': 'sac,dollar'},
  'evilz-potion-mort': {'font': 'evilz', 'code': 59464, 'theme': 'evilz', 'name': 'mort', 'search': 'potion,mort'},
});
