import ol_style_FontSymbol from 'ol-ext/style/FontSymbol'

/* Copyright (c) 2014 by Jean-Marc.Viglino [at]ign.fr
* Dual-licensed under the CeCILL-B Licence (http://www.cecill.info/)
* and the Beerware license (http://en.wikipedia.org/wiki/Beerware),
* feel free to use and abuse it in your projects (the code, not the beer ;-).
*
* Font definiton to use with fontsymbols
*/
ol_style_FontSymbol.addDefs ({
  'font': 'fontmaki',
  'name': 'Maki',
  'copyright': 'CC0 - MapBox - https://www.mapbox.com/maki/',
  'prefix': 'maki',
}, {
  'maki-bicycle': {'font': 'fontmaki', 'code': 59392, 'name': 'bicycle', 'search': 'velo,cycle,bicyclette', 'theme': 'transport'},
  'maki-building': {'font': 'fontmaki', 'code': 59393, 'name': 'building', 'search': 'maison,batiment', 'theme': 'construction'},
  'maki-bus': {'font': 'fontmaki', 'code': 59394, 'name': 'bus', 'search': 'bus', 'theme': 'transport'},
  'maki-cafe': {'font': 'fontmaki', 'code': 59395, 'name': 'cafe', 'search': 'cafe,bar', 'theme': 'service'},
  'maki-camera': {'font': 'fontmaki', 'code': 59396, 'name': 'camera', 'search': 'photo,appareil', 'theme': 'commerce'},
  'maki-campsite': {'font': 'fontmaki', 'code': 59397, 'name': 'campsite', 'search': 'camping,tente', 'theme': 'tourisme'},
  'maki-car': {'font': 'fontmaki', 'code': 59398, 'name': 'car', 'search': 'voiture', 'theme': 'transport'},
  'maki-cemetery': {'font': 'fontmaki', 'code': 59399, 'name': 'cemetery', 'search': 'cimetiere,tombe', 'theme': 'religion'},
  'maki-chemist': {'font': 'fontmaki', 'code': 59400, 'name': 'chemist', 'search': 'chemie,fiole', 'theme': 'industrie'},
  'maki-cinema': {'font': 'fontmaki', 'code': 59401, 'name': 'cinema', 'search': 'cinema,film', 'theme': 'tourisme'},
  'maki-circle': {'font': 'fontmaki', 'code': 59402, 'name': 'circle', 'search': 'cercle', 'theme': 'forme'},
  'maki-circle_stroked': {'font': 'fontmaki', 'code': 59403, 'name': 'circle_stroked', 'search': 'cercle,rond', 'theme': 'forme'},
  'maki-city': {'font': 'fontmaki', 'code': 59404, 'name': 'city', 'search': 'ville,batiment,hlm', 'theme': 'construction'},
  'maki-clothing_store': {'font': 'fontmaki', 'code': 59405, 'name': 'clothing_store', 'search': 'vetement,magasin', 'theme': 'commerce'},
  'maki-college': {'font': 'fontmaki', 'code': 59406, 'name': 'college', 'search': 'college,universite', 'theme': 'education'},
  'maki-commercial': {'font': 'fontmaki', 'code': 59407, 'name': 'commercial', 'search': 'commercial,tour', 'theme': 'construction'},
  'maki-cricket': {'font': 'fontmaki', 'code': 59408, 'name': 'cricket', 'search': 'cricket', 'theme': 'sport'},
  'maki-cross': {'font': 'fontmaki', 'code': 59409, 'name': 'cross', 'search': 'croix', 'theme': 'forme'},
  'maki-dam': {'font': 'fontmaki', 'code': 59410, 'name': 'dam', 'search': 'barrage,eau', 'theme': 'industrie'},
  'maki-danger': {'font': 'fontmaki', 'code': 59411, 'name': 'danger', 'search': 'danger,mort,tete', 'theme': 'panneau'},
  'maki-dentist': {'font': 'fontmaki', 'code': 59412, 'name': 'dentist', 'search': 'dentiste,sante', 'theme': 'service'},
  'maki-disability': {'font': 'fontmaki', 'code': 59413, 'name': 'disability', 'search': 'handicape', 'theme': 'service'},
  'maki-dog_park': {'font': 'fontmaki', 'code': 59414, 'name': 'dog_park', 'search': 'chien,parc', 'theme': 'service'},
  'maki-embassy': {'font': 'fontmaki', 'code': 59415, 'name': 'embassy', 'search': 'ambassade', 'theme': 'service'},
  'maki-emergency_telephone': {'font': 'fontmaki', 'code': 59416, 'name': 'emergency_telephone', 'search': 'telephone,urgence', 'theme': 'service'},
  'maki-entrance': {'font': 'fontmaki', 'code': 59417, 'name': 'entrance', 'search': 'entree', 'theme': 'construction'},
  'maki-farm': {'font': 'fontmaki', 'code': 59418, 'name': 'farm', 'search': 'ferme,batiment', 'theme': 'construction'},
  'maki-fast_food': {'font': 'fontmaki', 'code': 59419, 'name': 'fast_food', 'search': 'fast food,retaurant,hamburger', 'theme': 'commerce'},
  'maki-ferry': {'font': 'fontmaki', 'code': 59420, 'name': 'ferry', 'search': 'ferry,bac,bateau', 'theme': 'transport'},
  'maki-fire_station': {'font': 'fontmaki', 'code': 59421, 'name': 'fire_station', 'search': 'pompier,feu,station', 'theme': 'service'},
  'maki-fuel': {'font': 'fontmaki', 'code': 59422, 'name': 'fuel', 'search': 'pompe,essence', 'theme': 'commerce'},
  'maki-garden': {'font': 'fontmaki', 'code': 59423, 'name': 'garden', 'search': 'jardin,fleur', 'theme': 'loisir'},
  'maki-gift': {'font': 'fontmaki', 'code': 59424, 'name': 'gift', 'search': 'cadeau,achat', 'theme': 'commerce'},
  'maki-golf': {'font': 'fontmaki', 'code': 59425, 'name': 'golf', 'search': 'golf', 'theme': 'sport'},
  'maki-grocery': {'font': 'fontmaki', 'code': 59426, 'name': 'grocery', 'search': 'caddy,super,marche', 'theme': 'commerce'},
  'maki-hairdresser': {'font': 'fontmaki', 'code': 59427, 'name': 'hairdresser', 'search': 'coiffeur', 'theme': 'commerce'},
  'maki-harbor': {'font': 'fontmaki', 'code': 59428, 'name': 'harbor', 'search': 'port,bateau,ancre', 'theme': 'transport'},
  'maki-heart': {'font': 'fontmaki', 'code': 59429, 'name': 'heart', 'search': 'coeur,amour', 'theme': 'forme'},
  'maki-heliport': {'font': 'fontmaki', 'code': 59430, 'name': 'heliport', 'search': 'heliport,helicoptere', 'theme': 'transport'},
  'maki-hospital': {'font': 'fontmaki', 'code': 59431, 'name': 'hospital', 'search': 'hopital,croix', 'theme': 'service'},
  'maki-ice_cream': {'font': 'fontmaki', 'code': 59432, 'name': 'ice_cream', 'search': 'glace,cornet,enfant', 'theme': 'loisir'},
  'maki-industrial': {'font': 'fontmaki', 'code': 59433, 'name': 'industrial', 'search': 'industrie,usine', 'theme': 'industrie'},
  'maki-land_use': {'font': 'fontmaki', 'code': 59434, 'name': 'land_use', 'search': 'paysage', 'theme': 'paysage'},
  'maki-laundry': {'font': 'fontmaki', 'code': 59435, 'name': 'laundry', 'search': 'machine,laver,blanchisserie', 'theme': 'service'},
  'maki-library': {'font': 'fontmaki', 'code': 59436, 'name': 'library', 'search': 'livre,bibliotheque', 'theme': 'service'},
  'maki-lighthouse': {'font': 'fontmaki', 'code': 59437, 'name': 'lighthouse', 'search': 'phare,lumiere', 'theme': 'transport'},
  'maki-lodging': {'font': 'fontmaki', 'code': 59438, 'name': 'lodging', 'search': 'lit,hotel', 'theme': 'hebergement'},
  'maki-logging': {'font': 'fontmaki', 'code': 59439, 'name': 'logging', 'search': 'enregistrement', 'theme': 'hebergement'},
  'maki-london_underground': {'font': 'fontmaki', 'code': 59440, 'name': 'london_underground', 'search': 'underground,metro,londres', 'theme': 'transport'},
  'maki-marker': {'font': 'fontmaki', 'code': 59441, 'name': 'marker', 'search': 'marker,poi', 'theme': 'forme'},
  'maki-minefield': {'font': 'fontmaki', 'code': 59442, 'name': 'minefield', 'search': 'champ,mine', 'theme': 'paysage'},
  'maki-marker_stroked': {'font': 'fontmaki', 'code': 59443, 'name': 'marker_stroked', 'search': 'marker,poi', 'theme': 'forme'},
  'maki-mobilephone': {'font': 'fontmaki', 'code': 59444, 'name': 'mobilephone', 'search': 'mobile,telephone', 'theme': 'service'},
  'maki-monument': {'font': 'fontmaki', 'code': 59445, 'name': 'monument', 'search': 'monument,obelix,tour', 'theme': 'construction'},
  'maki-museum': {'font': 'fontmaki', 'code': 59446, 'name': 'museum', 'search': 'musee,maison', 'theme': 'tourisme'},
  'maki-music': {'font': 'fontmaki', 'code': 59447, 'name': 'music', 'search': 'musique,note', 'theme': 'loisir'},
  'maki-oil_well': {'font': 'fontmaki', 'code': 59448, 'name': 'oil_well', 'search': 'derrick,tour,pylone', 'theme': 'industrie'},
  'maki-park': {'font': 'fontmaki', 'code': 59449, 'name': 'park', 'search': 'parc,arbre,sapin', 'theme': 'paysage'},
  'maki-park2': {'font': 'fontmaki', 'code': 59450, 'name': 'park2', 'search': 'parc,arbre,feuillu', 'theme': 'paysage'},
  'maki-parking': {'font': 'fontmaki', 'code': 59451, 'name': 'parking', 'search': 'parking,p', 'theme': 'transport'},
  'maki-parking_garage': {'font': 'fontmaki', 'code': 59452, 'name': 'parking_garage', 'search': 'parking,garage', 'theme': 'transport'},
  'maki-pharmacy': {'font': 'fontmaki', 'code': 59453, 'name': 'pharmacy', 'search': 'pharmacie,medicament', 'theme': 'service'},
  'maki-pitch': {'font': 'fontmaki', 'code': 59454, 'name': 'pitch', 'search': 'saut,course', 'theme': 'sport'},
  'maki-playground': {'font': 'fontmaki', 'code': 59455, 'name': 'playground', 'search': 'balancoire,enfant,jardin', 'theme': 'loisir'},
  'maki-police': {'font': 'fontmaki', 'code': 59456, 'name': 'police', 'search': 'police,kepi', 'theme': 'service'},
  'maki-polling_place': {'font': 'fontmaki', 'code': 59457, 'name': 'polling_place', 'search': 'check,case,coche', 'theme': 'forme'},
  'maki-post': {'font': 'fontmaki', 'code': 59458, 'name': 'post', 'search': 'poste,lettre', 'theme': 'service'},
  'maki-prison': {'font': 'fontmaki', 'code': 59459, 'name': 'prison', 'search': 'prison,herse,barriere', 'theme': 'service'},
  'maki-rail': {'font': 'fontmaki', 'code': 59460, 'name': 'rail', 'search': 'rail,fer', 'theme': 'transport'},
  'maki-rail_above': {'font': 'fontmaki', 'code': 59461, 'name': 'rail_above', 'search': 'transport,train,sncf,rail,metro', 'theme': 'transport'},
  'maki-rail_light': {'font': 'fontmaki', 'code': 59462, 'name': 'rail_light', 'search': 'transport,train,sncf,rail', 'theme': 'transport'},
  'maki-rail_metro': {'font': 'fontmaki', 'code': 59463, 'name': 'rail_metro', 'search': 'transport,train,sncf,rail', 'theme': 'transport'},
  'maki-rail_underground': {'font': 'fontmaki', 'code': 59464, 'name': 'rail_underground', 'search': 'metro,rail', 'theme': 'transport'},
  'maki-religious-christian': {'font': 'fontmaki', 'code': 59465, 'theme': 'religion', 'name': 'christian', 'search': 'religion,chretien,coix'},
  'maki-religious-jewish': {'font': 'fontmaki', 'code': 59466, 'theme': 'religion', 'name': 'jewish', 'search': 'religion,juif,etoile'},
  'maki-religious-muslim': {'font': 'fontmaki', 'code': 59467, 'theme': 'religion', 'name': 'muslim', 'search': 'religion,musulman,etoile'},
  'maki-religious-place_of_worship': {'font': 'fontmaki', 'code': 59468, 'theme': 'religion', 'name': 'place_of_worship', 'search': 'religion,priere'},
  'maki-restaurant': {'font': 'fontmaki', 'code': 59469, 'name': 'restaurant', 'search': 'restaurant,fourchette,couteau', 'theme': 'service'},
  'maki-roadblock': {'font': 'fontmaki', 'code': 59470, 'name': 'roadblock', 'search': 'sens,interdit,panneau', 'theme': 'transport'},
  'maki-rocket': {'font': 'fontmaki', 'code': 59471, 'name': 'rocket', 'search': 'fus?e', 'theme': 'transport'},
  'maki-school': {'font': 'fontmaki', 'code': 59472, 'name': 'school', 'search': 'education,ecole,enfant,primaire', 'theme': 'education'},
  'maki-scooter': {'font': 'fontmaki', 'code': 59473, 'name': 'scooter', 'search': 'scooter,velo', 'theme': 'transport'},
  'maki-shop': {'font': 'fontmaki', 'code': 59474, 'name': 'shop', 'search': 'boutique,sac', 'theme': 'service'},
  'maki-skiing': {'font': 'fontmaki', 'code': 59475, 'name': 'skiing', 'search': 'ski,descente,montagne', 'theme': 'sport'},
  'maki-slaughterhouse': {'font': 'fontmaki', 'code': 59476, 'name': 'slaughterhouse', 'search': 'vache,animal,ferme', 'theme': 'industrie'},
  'maki-soccer': {'font': 'fontmaki', 'code': 59477, 'name': 'soccer', 'search': 'foot,ballon', 'theme': 'sport'},
  'maki-square': {'font': 'fontmaki', 'code': 59478, 'name': 'square', 'search': 'carre', 'theme': 'forme'},
  'maki-square_stroked': {'font': 'fontmaki', 'code': 59479, 'name': 'square_stroked', 'search': 'carre', 'theme': 'forme'},
  'maki-star': {'font': 'fontmaki', 'code': 59480, 'name': 'star', 'search': 'etoile', 'theme': 'forme'},
  'maki-star_stroked': {'font': 'fontmaki', 'code': 59481, 'name': 'star_stroked', 'search': 'etoile', 'theme': 'forme'},
  'maki-suitcase': {'font': 'fontmaki', 'code': 59482, 'name': 'suitcase', 'search': 'valise,voyage', 'theme': 'transport'},
  'maki-swimming': {'font': 'fontmaki', 'code': 59483, 'name': 'swimming', 'search': 'eau,nage,piscine', 'theme': 'sport'},
  'maki-telephone': {'font': 'fontmaki', 'code': 59484, 'name': 'telephone', 'search': 'telephone,urgence', 'theme': 'service'},
  'maki-tennis': {'font': 'fontmaki', 'code': 59485, 'name': 'tennis', 'search': 'tennis,balle,raquette', 'theme': 'sport'},
  'maki-theatre': {'font': 'fontmaki', 'code': 59486, 'name': 'theatre', 'search': 'theatre,culture', 'theme': 'tourisme'},
  'maki-toilets': {'font': 'fontmaki', 'code': 59487, 'name': 'toilets', 'search': 'toilettes,homme,femme', 'theme': 'service'},
  'maki-town': {'font': 'fontmaki', 'code': 59488, 'name': 'town', 'search': 'ville,maisons', 'theme': 'construction'},
  'maki-town_hall': {'font': 'fontmaki', 'code': 59489, 'name': 'town_hall', 'search': 'batiment,institution', 'theme': 'construction'},
  'maki-triangle': {'font': 'fontmaki', 'code': 59490, 'name': 'triangle', 'search': 'triangle', 'theme': 'forme'},
  'maki-triangle_stroked': {'font': 'fontmaki', 'code': 59491, 'name': 'triangle_stroked', 'search': 'triangle', 'theme': 'forme'},
  'maki-village': {'font': 'fontmaki', 'code': 59492, 'name': 'village', 'search': 'village,maison', 'theme': 'construction'},
  'maki-warehouse': {'font': 'fontmaki', 'code': 59493, 'name': 'warehouse', 'search': 'gite', 'theme': 'construction'},
  'maki-waste_basket': {'font': 'fontmaki', 'code': 59494, 'name': 'waste_basket', 'search': 'poubelle,recyclage', 'theme': 'service'},
  'maki-water': {'font': 'fontmaki', 'code': 59495, 'name': 'water', 'search': 'eau,goutte', 'theme': 'forme'},
  'maki-wetland': {'font': 'fontmaki', 'code': 59496, 'name': 'wetland', 'search': 'humide,riziere,marecage', 'theme': 'paysage'},
  'maki-zoo': {'font': 'fontmaki', 'code': 59497, 'name': 'zoo', 'search': 'zoo,girafe,animal', 'theme': 'loisir'},
  'maki-aerialway': {'font': 'fontmaki', 'code': 59498, 'name': 'aerialway', 'search': 'telepherique,ski,neige', 'theme': 'transport'},
  'maki-airfield': {'font': 'fontmaki', 'code': 59499, 'name': 'airfield', 'search': 'aerodrome,avion', 'theme': 'transport'},
  'maki-airport': {'font': 'fontmaki', 'code': 59500, 'name': 'airport', 'search': 'aeroport,avion', 'theme': 'transport'},
  'maki-alcohol_shop': {'font': 'fontmaki', 'code': 59501, 'name': 'alcohol_shop', 'search': 'boisson,alcool,vin,verre', 'theme': 'commerce'},
  'maki-america_football': {'font': 'fontmaki', 'code': 59502, 'name': 'america_football', 'search': 'fooball,rugby', 'theme': 'sport'},
  'maki-art_gallery': {'font': 'fontmaki', 'code': 59503, 'name': 'art_gallery', 'search': 'art,galerie,peinture', 'theme': 'loisir'},
  'maki-bakery': {'font': 'fontmaki', 'code': 59504, 'name': 'bakery', 'search': 'boulangerie,croissant', 'theme': 'commerce'},
  'maki-bank': {'font': 'fontmaki', 'code': 59505, 'name': 'bank', 'search': 'banque,carte,paiment', 'theme': 'service'},
  'maki-bar': {'font': 'fontmaki', 'code': 59506, 'name': 'bar', 'search': 'bar,coupe,verre,boisson', 'theme': 'commerce'},
  'maki-baseball': {'font': 'fontmaki', 'code': 59507, 'name': 'baseball', 'search': 'baseball', 'theme': 'sport'},
  'maki-basketball': {'font': 'fontmaki', 'code': 59508, 'name': 'basketball', 'search': 'basketball,ballon', 'theme': 'sport'},
  'maki-beer': {'font': 'fontmaki', 'code': 59509, 'name': 'beer', 'search': 'biere,boisson,cafe', 'theme': 'commerce'},
});
